### ISSUE TITLE
Auth middleware useDirectusUser is undefined

### ISSUE THREAD

**Issue by madsh93** [Intevel/nuxt-directus#8] opened 2022-03-31 14:01 UTC
nuxt-directus 1.1.4
nuxt: 3.0.0-27478897.169aa35

### Steps to reproduce
1. Create page /login.vue
2. Create page /index.vue and add
````js
definePageMeta({
  middleware: ["auth"]
})
````

3. Add middleware `/middleware/auth.ts`
````js
// /middleware/auth.ts
export default defineNuxtRouteMiddleware((to, from) => {
  const user = useDirectusUser()

  if (!user.value) {
    return navigateTo("/login")
  }
})
````

### What is Expected?
Using `const { login } = useDirectusAuth();` I should be able to sign in, refresh the page and stay signed in, as user.value is still defined.

### What is actually happening?
On refresh, the middleware kicks in again and this time returns `user.value` as undefined and redirects me to `/login`. Even though user.value is still defined.

### Workaround
Using `useDirectusToken()`seems to stay defined, and can be used as a workaround for auth middleware.

````js
// /middleware/auth.ts
export default defineNuxtRouteMiddleware((to, from) => {
  const token = useDirectusToken()

  if (!token.value) {
    return navigateTo("/login")
  }
})
````

**Comment by Intevel** [comment] 2022-03-31 20:17
This should be fixed if you run the `fetchUser()` method in the **middleware** again.

**Comment by Intevel** [comment] 2022-04-01 07:18
@madsh93 Im not able to reproduce this bug, but I know that it **can** exist. Same in the `strapi-module`.
Can you try run the fetchUser() method in the middleware again?

**Comment by casualmatt** [comment] 2022-04-03 14:30
@Intevel can you add an example on the documentation on what you suggest to do the Middleware to redirect the user if not login?

because i try to understand if there is a token in the cookies but is probably the wrong way to do it.

**Comment by casualmatt** [comment] 2022-04-04 11:29
For what i could debug, the issue is related to not having the refresh token, and if the session expire the user will be redirected on the login-page.

**Comment by Intevel** [comment] 2022-04-04 11:30
No I think this issue is not related to the refresh problem. The token has not expired yet, but it does not refresh the user correctly in the middleware.

**Comment by Intevel** [comment] 2022-04-05 11:32
@madsh93 Any updates on this?

**Closed** 2022-04-06 14:30 UTC
Labels: bug
